[profile.default]
solc = "0.8.24"
ffi = true
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 2
src = "src"
out = "out"
bytecode_hash = "none"
extra_output_files = [
  "abi",
  "evm.bytecode"
]

[fmt]
tab_width = 2
